# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1b045c0574eaf5d9baac93de9d4d42631626d9aec34dcd7745e21e381be01423099bb0181183bfefa7597b26e1f4e6d275737e630dc375e6f0aa40269d7596bd

test:
  secret_key_base: c0124203aa89b64a2029c929e274e59191ab6bcf06037e7d3f837e9e36e4e8aa32f0a064de55c1cd2de286b5a6f32ac94fe9b10e20f48a43099d0c79a34d04b2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
